// src/lib/budget-crop-data.ts

export interface Crop {
  id: string
  name: string
  category: 'vegetable' | 'fruit' | 'herb'
  heirloom_variety: string | null
  is_heirloom: boolean
  zone_min: number
  zone_max: number
  sun_requirement: 'full' | 'partial' | 'both'
  is_vertical: boolean
  yield_rating: number           // 1-5
  space_per_plant_sqft: number   // for land planner
  container_size: string         // for space planner
  min_ceiling_height: number     // feet minimum
  dual_use: { culinary: boolean; medicinal: boolean }
  seed_saving_difficulty: 'easy' | 'medium' | 'hard'
  seed_saving_notes: string
  planting_notes: string
  easy_win: boolean              // fast, beginner-friendly
}

export const CROPS: Crop[] = [

  // ─── VEGETABLES ────────────────────────────────────────────

  {
    id: 'tomato-cherokee-purple',
    name: 'Tomato',
    category: 'vegetable',
    heirloom_variety: 'Cherokee Purple',
    is_heirloom: true,
    zone_min: 3, zone_max: 11,
    sun_requirement: 'full',
    is_vertical: true,
    yield_rating: 5,
    space_per_plant_sqft: 4,
    container_size: '5 gallon',
    min_ceiling_height: 5,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Ferment seeds in water 2–3 days, rinse thoroughly, dry flat for 1 week. Store in cool, dry place.',
    planting_notes: 'Stake or cage for vertical growth. One of the highest-yield plants per sq ft when trellised.',
    easy_win: false,
  },
  {
    id: 'tomato-brandywine',
    name: 'Tomato',
    category: 'vegetable',
    heirloom_variety: 'Brandywine',
    is_heirloom: true,
    zone_min: 3, zone_max: 11,
    sun_requirement: 'full',
    is_vertical: true,
    yield_rating: 4,
    space_per_plant_sqft: 6,
    container_size: '10 gallon',
    min_ceiling_height: 5,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Ferment seeds 2–3 days, rinse, dry flat. Keep varieties isolated to avoid cross-pollination.',
    planting_notes: 'Large-fruited heirloom. Needs more space than slicing types but exceptional flavor and yield.',
    easy_win: false,
  },
  {
    id: 'pepper-california-wonder',
    name: 'Bell Pepper',
    category: 'vegetable',
    heirloom_variety: 'California Wonder',
    is_heirloom: true,
    zone_min: 4, zone_max: 11,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 2,
    container_size: '5 gallon',
    min_ceiling_height: 3,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Let pepper ripen fully to red on plant. Harvest seeds, rinse, dry 2 weeks before storing.',
    planting_notes: 'Excellent container crop. Full sun + consistent watering = heavy production.',
    easy_win: false,
  },
  {
    id: 'pepper-jimmy-nardello',
    name: 'Sweet Frying Pepper',
    category: 'vegetable',
    heirloom_variety: "Jimmy Nardello's",
    is_heirloom: true,
    zone_min: 5, zone_max: 11,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 5,
    space_per_plant_sqft: 2,
    container_size: '5 gallon',
    min_ceiling_height: 3,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Harvest from fully red fruit. Keep 50ft from other pepper varieties during flowering to prevent crossing.',
    planting_notes: 'Prolific and versatile — eat fresh, roast, or dry for storage. Great bang for the buck.',
    easy_win: false,
  },
  {
    id: 'cucumber-marketmore',
    name: 'Cucumber',
    category: 'vegetable',
    heirloom_variety: 'Marketmore 76',
    is_heirloom: true,
    zone_min: 3, zone_max: 11,
    sun_requirement: 'full',
    is_vertical: true,
    yield_rating: 5,
    space_per_plant_sqft: 1,
    container_size: '5 gallon',
    min_ceiling_height: 5,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Allow one fruit to yellow and fully mature on vine. Scoop seeds, rinse, dry flat.',
    planting_notes: 'Trellis for vertical growth — effectively doubles production per sq ft. Very fast-growing.',
    easy_win: true,
  },
  {
    id: 'bean-kentucky-wonder',
    name: 'Pole Bean',
    category: 'vegetable',
    heirloom_variety: 'Kentucky Wonder',
    is_heirloom: true,
    zone_min: 3, zone_max: 10,
    sun_requirement: 'full',
    is_vertical: true,
    yield_rating: 5,
    space_per_plant_sqft: 0.5,
    container_size: '5 gallon (3–4 plants)',
    min_ceiling_height: 5,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Leave pods on vine until dry and rattling. Shell and store in paper bag in a cool location.',
    planting_notes: 'Highest yield-per-sq-ft of any vegetable when trellised. Direct sow after last frost.',
    easy_win: true,
  },
  {
    id: 'pea-lincoln',
    name: 'Garden Pea',
    category: 'vegetable',
    heirloom_variety: 'Lincoln',
    is_heirloom: true,
    zone_min: 3, zone_max: 9,
    sun_requirement: 'both',
    is_vertical: true,
    yield_rating: 4,
    space_per_plant_sqft: 0.25,
    container_size: '5 gallon (6–8 plants)',
    min_ceiling_height: 4,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Let pods dry completely on vine before harvesting. Self-contained — easy to save.',
    planting_notes: 'Plant in early spring or fall. Cool-weather crop. Fixes nitrogen — improves soil for next planting.',
    easy_win: true,
  },
  {
    id: 'zucchini-black-beauty',
    name: 'Zucchini',
    category: 'vegetable',
    heirloom_variety: 'Black Beauty',
    is_heirloom: true,
    zone_min: 3, zone_max: 11,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 5,
    space_per_plant_sqft: 9,
    container_size: '15 gallon',
    min_ceiling_height: 3,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'medium',
    seed_saving_notes: 'Let one fruit grow to full maturity — large and yellow. Scoop seeds, rinse, dry flat.',
    planting_notes: 'Highest single-plant yield in the garden. Needs space but two plants feed a family.',
    easy_win: false,
  },
  {
    id: 'kale-red-russian',
    name: 'Kale',
    category: 'vegetable',
    heirloom_variety: 'Red Russian',
    is_heirloom: true,
    zone_min: 3, zone_max: 10,
    sun_requirement: 'both',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 2,
    container_size: '3 gallon',
    min_ceiling_height: 3,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'medium',
    seed_saving_notes: 'Biennial — let stalks bolt and flower second season. Harvest seed pods when dry and papery.',
    planting_notes: 'Cold hardy — extends growing season into winter. Cut-and-come-again for continuous harvest.',
    easy_win: true,
  },
  {
    id: 'lettuce-black-seeded-simpson',
    name: 'Lettuce',
    category: 'vegetable',
    heirloom_variety: 'Black Seeded Simpson',
    is_heirloom: true,
    zone_min: 3, zone_max: 10,
    sun_requirement: 'partial',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 1,
    container_size: '2 gallon or window box',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'medium',
    seed_saving_notes: 'Allow to bolt and flower. Shake dried seed heads into a paper bag.',
    planting_notes: 'Ready in 45 days. Partial shade prevents summer bolting. Great for windowsills.',
    easy_win: true,
  },
  {
    id: 'spinach-bloomsdale',
    name: 'Spinach',
    category: 'vegetable',
    heirloom_variety: 'Bloomsdale',
    is_heirloom: true,
    zone_min: 3, zone_max: 9,
    sun_requirement: 'partial',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 0.5,
    container_size: '2 gallon or window box',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'medium',
    seed_saving_notes: 'Allow plants to bolt. Harvest seed stalks when seeds are firm and brown. Separate male/female plants.',
    planting_notes: 'Cool season crop. Plant spring and fall. Extremely nutrient dense per sq ft.',
    easy_win: true,
  },
  {
    id: 'chard-rainbow',
    name: 'Swiss Chard',
    category: 'vegetable',
    heirloom_variety: 'Rainbow',
    is_heirloom: true,
    zone_min: 3, zone_max: 10,
    sun_requirement: 'both',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 1,
    container_size: '3 gallon',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Biennial — allow to bolt second year. Let seed stalks dry fully before harvesting.',
    planting_notes: 'Heat and cold tolerant. Cut-and-come-again. One of the most reliable budget crops.',
    easy_win: true,
  },
  {
    id: 'radish-cherry-belle',
    name: 'Radish',
    category: 'vegetable',
    heirloom_variety: 'Cherry Belle',
    is_heirloom: true,
    zone_min: 3, zone_max: 10,
    sun_requirement: 'both',
    is_vertical: false,
    yield_rating: 5,
    space_per_plant_sqft: 0.1,
    container_size: '2 gallon or window box',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Let one radish bolt and flower. Harvest dry seed pods when papery.',
    planting_notes: 'Ready in 22–25 days. Best immediate-gratification crop for new growers.',
    easy_win: true,
  },
  {
    id: 'carrot-danvers',
    name: 'Carrot',
    category: 'vegetable',
    heirloom_variety: 'Danvers 126',
    is_heirloom: true,
    zone_min: 3, zone_max: 10,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 0.1,
    container_size: '12-inch deep pot',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'medium',
    seed_saving_notes: 'Biennial — overwinter plant, harvest seeds from flower heads second year.',
    planting_notes: 'Loosen soil 12" deep. Thin to 2" apart. Stores in ground through winter in zones 5+.',
    easy_win: false,
  },
  {
    id: 'garlic-music',
    name: 'Garlic',
    category: 'vegetable',
    heirloom_variety: 'Music (Hardneck)',
    is_heirloom: true,
    zone_min: 3, zone_max: 9,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 0.25,
    container_size: '3 gallon (6 cloves)',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Save the largest bulbs at harvest. Replant individual cloves each fall. One bulb = 8–12 cloves.',
    planting_notes: 'Plant fall, harvest next summer. Medicinal: antimicrobial, immune support, cardiovascular.',
    easy_win: false,
  },
  {
    id: 'sweet-potato-beauregard',
    name: 'Sweet Potato',
    category: 'vegetable',
    heirloom_variety: 'Beauregard',
    is_heirloom: false,
    zone_min: 7, zone_max: 11,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 5,
    space_per_plant_sqft: 9,
    container_size: '15 gallon grow bag',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Save slips from stored tubers each spring. No seed saving required — propagate from roots.',
    planting_notes: 'Very high calorie yield per sq ft. Vines can be trellised to save ground space.',
    easy_win: false,
  },
  {
    id: 'okra-clemson-spineless',
    name: 'Okra',
    category: 'vegetable',
    heirloom_variety: 'Clemson Spineless',
    is_heirloom: true,
    zone_min: 7, zone_max: 11,
    sun_requirement: 'full',
    is_vertical: true,
    yield_rating: 4,
    space_per_plant_sqft: 4,
    container_size: '5 gallon',
    min_ceiling_height: 5,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Leave pods on plant until fully dry and brown. Shell and store in paper bag.',
    planting_notes: 'Thrives in heat. Tall vertical grower. Pick pods at 3–4" for best flavor.',
    easy_win: false,
  },

  // ─── FRUITS ────────────────────────────────────────────────

  {
    id: 'strawberry-ozark-beauty',
    name: 'Strawberry',
    category: 'fruit',
    heirloom_variety: 'Ozark Beauty',
    is_heirloom: true,
    zone_min: 3, zone_max: 9,
    sun_requirement: 'full',
    is_vertical: true,
    yield_rating: 4,
    space_per_plant_sqft: 1,
    container_size: 'Vertical grow bag or hanging basket',
    min_ceiling_height: 3,
    dual_use: { culinary: true, medicinal: false },
    seed_saving_difficulty: 'hard',
    seed_saving_notes: 'Propagate via runners — cut runner plantlets in late summer. Seed saving impractical.',
    planting_notes: 'Everbearing — two harvests per season. Ideal for vertical grow bags and small spaces.',
    easy_win: false,
  },
  {
    id: 'blueberry-patriot',
    name: 'Blueberry',
    category: 'fruit',
    heirloom_variety: null,
    is_heirloom: false,
    zone_min: 3, zone_max: 7,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 16,
    container_size: '15–25 gallon',
    min_ceiling_height: 4,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'hard',
    seed_saving_notes: 'Propagate via stem cuttings in spring. Not practical for seed saving.',
    planting_notes: 'Perennial — plant once, harvest 15–20 years. Needs acidic soil (pH 4.5–5.5). High antioxidant medicinal value.',
    easy_win: false,
  },

  // ─── HERBS (dual use) ──────────────────────────────────────

  {
    id: 'basil-genovese',
    name: 'Basil',
    category: 'herb',
    heirloom_variety: 'Genovese',
    is_heirloom: true,
    zone_min: 4, zone_max: 11,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 1,
    container_size: '1 gallon',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Allow flower spikes to dry fully on plant. Shake seeds into paper bag.',
    planting_notes: 'Anti-inflammatory and antimicrobial. Grow near tomatoes for companion planting benefit.',
    easy_win: true,
  },
  {
    id: 'rosemary-common',
    name: 'Rosemary',
    category: 'herb',
    heirloom_variety: null,
    is_heirloom: false,
    zone_min: 6, zone_max: 11,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 3,
    space_per_plant_sqft: 4,
    container_size: '3 gallon',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'hard',
    seed_saving_notes: 'Propagate via stem cuttings — much easier and more reliable than seed.',
    planting_notes: 'Perennial in zones 6+. Antimicrobial, circulation support, memory and focus aid.',
    easy_win: false,
  },
  {
    id: 'thyme-german',
    name: 'Thyme',
    category: 'herb',
    heirloom_variety: 'German',
    is_heirloom: true,
    zone_min: 4, zone_max: 9,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 3,
    space_per_plant_sqft: 1,
    container_size: '1 gallon',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'medium',
    seed_saving_notes: 'Allow to flower and set seed. Shake dried flower heads into bag.',
    planting_notes: 'Perennial. Antimicrobial, respiratory support. Drought tolerant once established.',
    easy_win: true,
  },
  {
    id: 'mint-spearmint',
    name: 'Spearmint',
    category: 'herb',
    heirloom_variety: null,
    is_heirloom: false,
    zone_min: 3, zone_max: 11,
    sun_requirement: 'partial',
    is_vertical: false,
    yield_rating: 5,
    space_per_plant_sqft: 2,
    container_size: '1 gallon (contain in pot)',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Propagate via runners or stem cuttings. Very aggressive spreader — always contain in pots.',
    planting_notes: 'Digestive aid, headache relief, natural pest deterrent. Always grow in containers.',
    easy_win: true,
  },
  {
    id: 'lavender-hidcote',
    name: 'Lavender',
    category: 'herb',
    heirloom_variety: 'Hidcote',
    is_heirloom: false,
    zone_min: 5, zone_max: 9,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 3,
    space_per_plant_sqft: 4,
    container_size: '3 gallon',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'medium',
    seed_saving_notes: 'Allow flower stalks to dry fully. Shake seeds from dried heads.',
    planting_notes: 'Perennial. Anxiety relief, sleep aid, antibacterial. One of the most profitable herbs to sell.',
    easy_win: false,
  },
  {
    id: 'chamomile-german',
    name: 'German Chamomile',
    category: 'herb',
    heirloom_variety: null,
    is_heirloom: false,
    zone_min: 3, zone_max: 9,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 1,
    container_size: '1 gallon',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Self-seeds readily. Collect from dried flower heads. Will naturalize in garden on its own.',
    planting_notes: 'Self-seeding annual. Anti-inflammatory, sleep aid, digestive support. Essentially free after first season.',
    easy_win: true,
  },
  {
    id: 'echinacea-purpurea',
    name: 'Echinacea',
    category: 'herb',
    heirloom_variety: 'Magnus',
    is_heirloom: false,
    zone_min: 3, zone_max: 9,
    sun_requirement: 'full',
    is_vertical: false,
    yield_rating: 3,
    space_per_plant_sqft: 2,
    container_size: '3 gallon',
    min_ceiling_height: 3,
    dual_use: { culinary: false, medicinal: true },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Allow seed heads to dry fully on plant through fall. Shake into bag.',
    planting_notes: 'Perennial. Immune support. Roots, leaves, and flowers all usable medicinally.',
    easy_win: false,
  },
  {
    id: 'lemon-balm',
    name: 'Lemon Balm',
    category: 'herb',
    heirloom_variety: null,
    is_heirloom: false,
    zone_min: 3, zone_max: 9,
    sun_requirement: 'partial',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 2,
    container_size: '2 gallon',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Self-seeds freely. Collect from dried flower whorls in late summer.',
    planting_notes: 'Stress relief, antiviral, digestive aid. Tolerates partial shade — good for lower-light spaces.',
    easy_win: true,
  },
  {
    id: 'calendula-resina',
    name: 'Calendula',
    category: 'herb',
    heirloom_variety: 'Resina',
    is_heirloom: true,
    zone_min: 2, zone_max: 11,
    sun_requirement: 'both',
    is_vertical: false,
    yield_rating: 4,
    space_per_plant_sqft: 1,
    container_size: '1 gallon',
    min_ceiling_height: 2,
    dual_use: { culinary: true, medicinal: true },
    seed_saving_difficulty: 'easy',
    seed_saving_notes: 'Seeds are crescent-shaped and cluster on spent flower heads. Easy to see and collect.',
    planting_notes: 'Anti-inflammatory, skin healing. Edible flowers. Resists light frost. Grows nearly anywhere.',
    easy_win: true,
  },
]
