"use client"

import { Navigation } from "@/components/Navigation"
import { Leaf } from "lucide-react"
import Link from "next/link"

const LAST_UPDATED = "April 26, 2025"
const CONTACT_EMAIL = "support@thesteadcraft.com"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background pb-24 pt-20">
      <Navigation />
      <main className="container mx-auto max-w-3xl px-4 pt-12">

        {/* Header */}
        <div className="mb-12 flex flex-col items-start gap-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground">
              <Leaf className="h-5 w-5 fill-current" />
            </div>
            <span className="font-headline text-xl font-bold text-primary">SteadCraft</span>
          </div>
          <h1 className="font-headline text-4xl font-bold text-foreground">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
          <div className="h-px w-full bg-border/40" />
        </div>

        {/* Intro */}
        <div className="prose prose-sm max-w-none space-y-10 text-foreground/80">

          <section className="space-y-3">
            <p className="leading-relaxed">
              Welcome to SteadCraft. By creating an account or using our services, you agree to these Terms of Service. Please read them carefully. If you do not agree, do not use SteadCraft.
            </p>
            <p className="leading-relaxed">
              These terms apply to all users of SteadCraft, including free-tier users, paid subscribers, and guests using anonymous access.
            </p>
          </section>

          <Section title="1. What SteadCraft Is">
            <p>
              SteadCraft is an AI-powered homesteading & DIY and DIY assistant that generates project instructions, tool lists, safety guidance, and step-by-step guides. Our content is generated by artificial intelligence and is intended for informational and educational purposes only.
            </p>
          </Section>

          <Section title="2. AI-Generated Content">
            <p>
              All project guides, instructions, safety precautions, tool recommendations, and clarifications are generated by AI models. You acknowledge and agree that:
            </p>
            <ul>
              <li>AI-generated content may contain errors, omissions, or outdated information.</li>
              <li>SteadCraft does not guarantee the accuracy, completeness, or fitness of any AI-generated guide for any particular purpose.</li>
              <li>You are solely responsible for verifying any instructions before carrying them out, particularly for electrical, structural, plumbing, food safety, and any other work that may pose safety risks.</li>
              <li>For complex, regulated, or high-risk work, always consult a licensed professional in the relevant trade.</li>
              <li>SteadCraft&apos;s AI guidance does not replace professional advice and should never be treated as such.</li>
            </ul>
          </Section>

          <Section title="3. Safety Disclaimer">
            <p>
              DIY projects carry inherent risks. You assume all responsibility for any injury, property damage, or other harm that results from following instructions provided by SteadCraft. Always:
            </p>
            <ul>
              <li>Wear appropriate personal protective equipment (PPE).</li>
              <li>Follow all applicable local building codes, regulations, and permit requirements.</li>
              <li>Consult a licensed contractor, electrician, plumber, or other professional when the work requires it.</li>
              <li>Use tools and materials only as intended by their manufacturers.</li>
            </ul>
            <p>
              SteadCraft, its owners, and its operators are not liable for any damages, injuries, or losses arising from the use of information provided through the service.
            </p>
          </Section>

          <Section title="4. Accounts and Access">
            <p>
              You may use SteadCraft with a full account (email and password) or as an anonymous guest. You are responsible for:
            </p>
            <ul>
              <li>Keeping your login credentials secure and confidential.</li>
              <li>All activity that occurs under your account.</li>
              <li>Notifying us immediately if you believe your account has been compromised.</li>
            </ul>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms, engage in abuse, or are used for fraudulent purposes.
            </p>
          </Section>

          <Section title="5. Subscriptions and Payments">
            <p>
              SteadCraft offers a free tier with limited project credits and a paid Pro subscription with unlimited access. By subscribing to a paid plan:
            </p>
            <ul>
              <li>You authorise us to charge your payment method on a recurring basis at the rate displayed at the time of purchase.</li>
              <li>Payments are processed securely through Stripe. SteadCraft does not store your credit card details.</li>
              <li>You may cancel your subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period — no partial refunds are issued.</li>
              <li>We reserve the right to change pricing with reasonable advance notice.</li>
            </ul>
          </Section>

          <Section title="6. User Content">
            <p>
              When you submit content to SteadCraft — including build log notes, photos, and tool reviews — you grant us a non-exclusive, royalty-free licence to display that content within the service. You retain ownership of your content.
            </p>
            <p>
              You agree not to submit content that is unlawful, harmful, defamatory, infringing on third-party rights, or otherwise objectionable. We reserve the right to remove content that violates these standards.
            </p>
          </Section>

          <Section title="7. Public Build Logs">
            <p>
              If you mark a build log entry as public, it will be visible to other SteadCraft users and anyone with the shareable link. You are responsible for ensuring that anything you make public does not contain private, sensitive, or copyrighted material belonging to others.
            </p>
          </Section>

          <Section title="8. Intellectual Property">
            <p>
              The SteadCraft name, logo, interface design, and proprietary software are the intellectual property of SteadCraft and its operators. You may not reproduce, distribute, or create derivative works based on our materials without written permission.
            </p>
          </Section>

          <Section title="9. Prohibited Uses">
            <p>You agree not to use SteadCraft to:</p>
            <ul>
              <li>Attempt to gain unauthorised access to any part of the service or its infrastructure.</li>
              <li>Scrape, harvest, or systematically collect data from the platform.</li>
              <li>Use automated tools, bots, or scripts to generate content at scale.</li>
              <li>Resell or sublicence access to the service.</li>
              <li>Violate any applicable local, state, national, or international law.</li>
            </ul>
          </Section>

          <Section title="10. Disclaimer of Warranties">
            <p>
              SteadCraft is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, error-free, or free of harmful components.
            </p>
          </Section>

          <Section title="11. Limitation of Liability">
            <p>
              To the maximum extent permitted by applicable law, SteadCraft and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service, including but not limited to personal injury, property damage, data loss, or financial loss.
            </p>
          </Section>

          <Section title="12. Changes to These Terms">
            <p>
              We may update these Terms of Service from time to time. We will notify you of significant changes by updating the &quot;Last updated&quot; date at the top of this page. Continued use of SteadCraft after changes are posted constitutes your acceptance of the revised terms.
            </p>
          </Section>

          <Section title="13. Contact">
            <p>
              If you have questions about these terms, please contact us at{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline hover:text-primary/80">
                {CONTACT_EMAIL}
              </a>.
            </p>
          </Section>

          <div className="h-px w-full bg-border/40 pt-4" />
          <div className="flex items-center justify-between pt-2 text-xs text-muted-foreground">
            <span>SteadCraft &mdash; {LAST_UPDATED}</span>
            <Link href="/privacy" className="text-primary hover:underline">Privacy Policy →</Link>
          </div>
        </div>
      </main>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="font-headline text-lg font-bold text-foreground">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-foreground/80">{children}</div>
    </section>
  )
}